# Generated by Django 5.2.9 on 2026-01-04 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Secret name (e.g., DEPLOY_TOKEN, AWS_SECRET_KEY)', max_length=100)),
                ('encrypted_value', models.BinaryField()),
                ('scope', models.CharField(choices=[('organization', 'Organization'), ('pipeline', 'Pipeline')], default='organization', max_length=20)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='pipelines.pipeline')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecretVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('encrypted_value', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='secrets.secret')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='secret',
            index=models.Index(fields=['tenant', 'scope'], name='secrets_sec_tenant__94d0a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together={('tenant', 'pipeline', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='secretversion',
            unique_together={('secret', 'version')},
        ),
    ]
