# Generated by Django 5.2.9 on 2026-01-04 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('runner_type', models.CharField(choices=[('shared', 'Shared'), ('dedicated', 'Dedicated'), ('self_hosted', 'Self-Hosted')], default='self_hosted', max_length=20)),
                ('labels', models.JSONField(default=list)),
                ('capabilities', models.JSONField(default=dict, help_text='Available executors: docker, shell, etc.')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('system_info', models.JSONField(default=dict, help_text='OS, CPU, memory, etc.')),
                ('max_concurrent_jobs', models.PositiveIntegerField(default=2)),
                ('current_jobs', models.PositiveIntegerField(default=0)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runners', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'runner_type'], name='runners_run_status_1bafd8_idx'), models.Index(fields=['tenant', 'status'], name='runners_run_tenant__d0fcae_idx')],
            },
        ),
    ]
