# Generated by Django 5.2.9 on 2026-01-04 08:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipelines', '0001_initial'),
        ('runners', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('trigger_type', models.CharField(choices=[('push', 'Push'), ('pull_request', 'Pull Request'), ('schedule', 'Schedule'), ('manual', 'Manual'), ('webhook', 'Webhook'), ('api', 'API')], max_length=20)),
                ('trigger_info', models.JSONField(default=dict, help_text='Details about the trigger: commit SHA, branch, user, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.JSONField(default=dict, help_text='Environment variables for this execution')),
                ('inputs', models.JSONField(default=dict, help_text='Inputs for workflow_dispatch trigger')),
                ('concurrency_group', models.CharField(blank=True, max_length=200)),
                ('concurrency_cancel_in_progress', models.BooleanField(default=False)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pipelines.pipeline')),
                ('pipeline_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='pipelines.pipelineconfig')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('job_key', models.CharField(help_text='Key used in YAML (e.g., "build", "test")', max_length=100)),
                ('needs', models.JSONField(default=list, help_text='List of job keys this job depends on')),
                ('condition', models.TextField(blank=True, help_text='if: condition expression')),
                ('matrix_values', models.JSONField(default=dict, help_text='Matrix variable values for this job instance')),
                ('runs_on', models.JSONField(default=list, help_text='Required runner labels')),
                ('container', models.JSONField(default=dict, help_text='Container configuration: image, options, env, volumes')),
                ('services', models.JSONField(default=dict, help_text='Service containers for this job')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('timeout_minutes', models.PositiveIntegerField(default=60)),
                ('outputs', models.JSONField(default=dict, help_text='Job outputs that can be referenced by dependent jobs')),
                ('environment', models.JSONField(default=dict, help_text='Environment variables for this job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='executions.execution')),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='runners.runner')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('run', 'Run Command'), ('uses', 'Use Action')], max_length=20)),
                ('run_command', models.TextField(blank=True, help_text='Shell command to run')),
                ('shell', models.CharField(default='bash', max_length=20)),
                ('working_directory', models.CharField(blank=True, max_length=500)),
                ('uses_action', models.CharField(blank=True, help_text='Action reference: owner/repo@version', max_length=200)),
                ('with_inputs', models.JSONField(default=dict, help_text='Inputs for the action')),
                ('env', models.JSONField(default=dict, help_text='Environment variables for this step')),
                ('condition', models.TextField(blank=True, help_text='if: condition expression')),
                ('continue_on_error', models.BooleanField(default=False)),
                ('timeout_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outputs', models.JSONField(default=dict, help_text='Step outputs set via ::set-output')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='executions.job')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['tenant', 'status'], name='executions__tenant__8303bd_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['pipeline', '-number'], name='executions__pipelin_0ff0a9_idx'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['status', 'queued_at'], name='executions__status_798484_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='execution',
            unique_together={('pipeline', 'number')},
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['execution', 'status'], name='executions__executi_7e70fb_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['runner', 'status'], name='executions__runner__0a7546_idx'),
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['job', 'order'], name='executions__job_id_f33c72_idx'),
        ),
    ]
