# Generated by Django 5.2.9 on 2026-01-04 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Artifact name for reference', max_length=200)),
                ('storage_path', models.CharField(help_text='Path in storage backend', max_length=500)),
                ('size_bytes', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('expires_at', models.DateTimeField()),
                ('file_count', models.PositiveIntegerField(default=1)),
                ('is_compressed', models.BooleanField(default=True)),
                ('compression_type', models.CharField(blank=True, default='gzip', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
