# Generated by Django 5.2.9 on 2026-01-04 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
        ('executions', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='executions.execution'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='executions.job'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='artifactdownload',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='artifacts.artifact'),
        ),
        migrations.AddField(
            model_name='artifactdownload',
            name='downloaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['execution', 'name'], name='artifacts_a_executi_8afaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['expires_at'], name='artifacts_a_expires_ad7d03_idx'),
        ),
    ]
