# Generated by Django 5.2.9 on 2026-01-04 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_chunks', to='executions.step')),
            ],
            options={
                'ordering': ['chunk_number'],
                'indexes': [models.Index(fields=['step', 'chunk_number'], name='logs_logchu_step_id_09ccb3_idx')],
                'unique_together': {('step', 'chunk_number')},
            },
        ),
    ]
