# Generated by Django 5.2.9 on 2026-01-04 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('repository_url', models.URLField(blank=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('config_path', models.CharField(default='.muelsyse/pipeline.yml', help_text='Path to the pipeline configuration file in the repository', max_length=200)),
                ('triggers', models.JSONField(default=dict, help_text='Trigger configuration: push, pull_request, schedule, workflow_dispatch')),
                ('webhook_secret', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_execution_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('config_yaml', models.TextField()),
                ('parsed_config', models.JSONField(default=dict)),
                ('commit_sha', models.CharField(blank=True, max_length=40)),
                ('commit_message', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='pipelines.pipeline')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['tenant', 'is_active'], name='pipelines_p_tenant__d5305d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipeline',
            unique_together={('tenant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='pipelineconfig',
            unique_together={('pipeline', 'version')},
        ),
    ]
