# Generated by Django 5.2.9 on 2026-01-04 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Professional'), ('enterprise', 'Enterprise'), ('self_hosted', 'Self-Hosted')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('max_runners', models.PositiveIntegerField(default=3)),
                ('max_concurrent_jobs', models.PositiveIntegerField(default=5)),
                ('max_retention_days', models.PositiveIntegerField(default=30)),
                ('storage_quota_mb', models.PositiveIntegerField(default=1024)),
                ('current_storage_mb', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
